// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARQo9jSqvEziwngBBjLB4SUsGPUJ5pRfQ',
    appId: '1:131923740762:web:b49a254706de1955287063',
    messagingSenderId: '131923740762',
    projectId: 'flutter-todo-f62d6',
    authDomain: 'flutter-todo-f62d6.firebaseapp.com',
    storageBucket: 'flutter-todo-f62d6.firebasestorage.app',
    measurementId: 'G-B6V3E3WE3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUTS41d-9_2BG5szUIDBZEES6oFrX4NfA',
    appId: '1:131923740762:android:ac0a3be59feb6cb2287063',
    messagingSenderId: '131923740762',
    projectId: 'flutter-todo-f62d6',
    storageBucket: 'flutter-todo-f62d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo02IsV2-Fh8YhSM5ce2OK8Sd1yQRQ0Ec',
    appId: '1:131923740762:ios:ed2e98f3ab48df83287063',
    messagingSenderId: '131923740762',
    projectId: 'flutter-todo-f62d6',
    storageBucket: 'flutter-todo-f62d6.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo02IsV2-Fh8YhSM5ce2OK8Sd1yQRQ0Ec',
    appId: '1:131923740762:ios:ed2e98f3ab48df83287063',
    messagingSenderId: '131923740762',
    projectId: 'flutter-todo-f62d6',
    storageBucket: 'flutter-todo-f62d6.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARQo9jSqvEziwngBBjLB4SUsGPUJ5pRfQ',
    appId: '1:131923740762:web:46b56ae815693aa7287063',
    messagingSenderId: '131923740762',
    projectId: 'flutter-todo-f62d6',
    authDomain: 'flutter-todo-f62d6.firebaseapp.com',
    storageBucket: 'flutter-todo-f62d6.firebasestorage.app',
    measurementId: 'G-XFL92TLHQ1',
  );
}
