// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByAcpwbykpsGnnhgY3wQfp1SNwOcbN1o8',
    appId: '1:910837320577:web:05224684d0b3ce67a53680',
    messagingSenderId: '910837320577',
    projectId: 'flutter-todo-tut-app',
    authDomain: 'flutter-todo-tut-app.firebaseapp.com',
    storageBucket: 'flutter-todo-tut-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb0fuYkKTk5nxPwZ-V6zAvVy8Yg_-jBWk',
    appId: '1:910837320577:android:ca9325042f0ac424a53680',
    messagingSenderId: '910837320577',
    projectId: 'flutter-todo-tut-app',
    storageBucket: 'flutter-todo-tut-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2jclmJX-ig5zYe_xWyA8PWBGpUABRnzM',
    appId: '1:910837320577:ios:7c5dd18796928e00a53680',
    messagingSenderId: '910837320577',
    projectId: 'flutter-todo-tut-app',
    storageBucket: 'flutter-todo-tut-app.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2jclmJX-ig5zYe_xWyA8PWBGpUABRnzM',
    appId: '1:910837320577:ios:7c5dd18796928e00a53680',
    messagingSenderId: '910837320577',
    projectId: 'flutter-todo-tut-app',
    storageBucket: 'flutter-todo-tut-app.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByAcpwbykpsGnnhgY3wQfp1SNwOcbN1o8',
    appId: '1:910837320577:web:6038b40f0de1b839a53680',
    messagingSenderId: '910837320577',
    projectId: 'flutter-todo-tut-app',
    authDomain: 'flutter-todo-tut-app.firebaseapp.com',
    storageBucket: 'flutter-todo-tut-app.firebasestorage.app',
  );
}
